services:
  api:
    build:
      context: ./hotnews_project
    container_name: hotnews_api
    environment:
      BACKEND_CORS_ORIGINS: http://127.0.0.1:5173,http://localhost:5173,http://127.0.0.1:8080,http://localhost:8080
    volumes:
      - ./hotnews_project/data:/app/data
    ports:
      - "8000:8000"

  web:
    build:
      context: ./hotnews_web
    container_name: hotnews_web
    depends_on:
      - api
    ports:
      - "8080:80"
